---
abstract: 'stop processing the entire test suite'
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  Test::More: 0
  Test::Run::CmdLine::Trap::ProveApp: 0
  Test::Trap: 0
configure_requires:
  Module::Build: 0.39
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Run-Plugin-BreakOnFailure
provides:
  Test::Run::CmdLine::Plugin::BreakOnFailure:
    file: lib/Test/Run/CmdLine/Plugin/BreakOnFailure.pm
    version: v0.0.2
  Test::Run::Plugin::BreakOnFailure:
    file: lib/Test/Run/Plugin/BreakOnFailure.pm
    version: v0.0.2
requires:
  MRO::Compat: 0
  Moose: 0
  Test::Run::CmdLine: 0.0120
  Test::Run::Core: 0.0120
resources:
  license: http://www.opensource.org/licenses/mit-license.php
version: v0.0.2
